export type LibraryItem = {
  name: string;
  category: "Supplement" | "Peptide" | "Compound";
  defaultForm: string;
  defaultUnit: string;
  defaultDose?: string;
  description?: string;
};

export const LIBRARY: LibraryItem[] = [
  // ── MAGNESIUM FORMS ──────────────────────────────────────────────────────────
  { name: "Magnesium Glycinate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Magnesium Malate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Magnesium L-Threonate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "2000" },
  { name: "Magnesium Acetyl Taurate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "700" },
  { name: "Magnesium Sucrosomial", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "350" },
  { name: "Magnesium Citrate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Magnesium Orotate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Magnesium Sulfate (Epsom)", category: "Supplement", defaultForm: "Bath", defaultUnit: "g", defaultDose: "200" },
  { name: "Magnesium Taurate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Magnesium Bisglycinate", category: "Supplement", defaultForm: "Powder", defaultUnit: "mg", defaultDose: "300" },

  // ── VITAMINS ─────────────────────────────────────────────────────────────────
  { name: "Vitamin D3", category: "Supplement", defaultForm: "Softgel", defaultUnit: "IU", defaultDose: "5000" },
  { name: "Vitamin D3 + K2", category: "Supplement", defaultForm: "Softgel", defaultUnit: "IU", defaultDose: "5000" },
  { name: "Vitamin K2 (MK-7)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mcg", defaultDose: "100" },
  { name: "Vitamin K2 (MK-4)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "5" },
  { name: "Vitamin C", category: "Supplement", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "1000" },
  { name: "Liposomal Vitamin C", category: "Supplement", defaultForm: "Liquid", defaultUnit: "mg", defaultDose: "1000" },
  { name: "Vitamin E (Mixed Tocopherols)", category: "Supplement", defaultForm: "Softgel", defaultUnit: "mg", defaultDose: "200" },
  { name: "Vitamin A (Retinol)", category: "Supplement", defaultForm: "Softgel", defaultUnit: "IU", defaultDose: "5000" },
  { name: "Beta-Carotene", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "15" },
  { name: "Vitamin B1 (Thiamine)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "Vitamin B2 (Riboflavin)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "Vitamin B3 (Niacinamide)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Vitamin B3 (Nicotinic Acid)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Vitamin B5 (Pantothenic Acid)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Vitamin B6 (P5P)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "50" },
  { name: "Vitamin B12 (Methylcobalamin)", category: "Supplement", defaultForm: "Sublingual", defaultUnit: "mcg", defaultDose: "1000" },
  { name: "Vitamin B12 (Adenosylcobalamin)", category: "Supplement", defaultForm: "Sublingual", defaultUnit: "mcg", defaultDose: "1000" },
  { name: "Vitamin B12 (Hydroxocobalamin)", category: "Supplement", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "1000" },
  { name: "Methylfolate (5-MTHF)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mcg", defaultDose: "400" },
  { name: "Folinic Acid", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mcg", defaultDose: "800" },
  { name: "P5P (Active B6)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "50" },
  { name: "Benfotiamine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "150" },
  { name: "Allithiamine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "50" },
  { name: "Biotin", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mcg", defaultDose: "5000" },
  { name: "B-Complex", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1" },
  { name: "Inositol (Myo-Inositol)", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "2" },
  { name: "Inositol (D-Chiro-Inositol)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "600" },
  { name: "PABA (Para-Aminobenzoic Acid)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Choline Bitartrate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },

  // ── OMEGA FATTY ACIDS ────────────────────────────────────────────────────────
  { name: "Omega-3 Fish Oil", category: "Supplement", defaultForm: "Softgel", defaultUnit: "mg", defaultDose: "1000" },
  { name: "Cod Liver Oil", category: "Supplement", defaultForm: "Liquid", defaultUnit: "ml", defaultDose: "5" },
  { name: "Krill Oil", category: "Supplement", defaultForm: "Softgel", defaultUnit: "mg", defaultDose: "500" },
  { name: "Algae Omega-3 (DHA/EPA)", category: "Supplement", defaultForm: "Softgel", defaultUnit: "mg", defaultDose: "500" },
  { name: "Evening Primrose Oil (GLA)", category: "Supplement", defaultForm: "Softgel", defaultUnit: "mg", defaultDose: "500" },
  { name: "Black Currant Seed Oil", category: "Supplement", defaultForm: "Softgel", defaultUnit: "mg", defaultDose: "500" },
  { name: "Flaxseed Oil (ALA)", category: "Supplement", defaultForm: "Softgel", defaultUnit: "mg", defaultDose: "1000" },

  // ── MINERALS ─────────────────────────────────────────────────────────────────
  { name: "Zinc Picolinate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "30" },
  { name: "Zinc Gluconate", category: "Supplement", defaultForm: "Lozenge", defaultUnit: "mg", defaultDose: "15" },
  { name: "Zinc Bisglycinate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "25" },
  { name: "Zinc Carnosine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "75" },
  { name: "Iron Bisglycinate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "25" },
  { name: "Ferrous Sulfate", category: "Supplement", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "325" },
  { name: "Calcium Citrate", category: "Supplement", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "500" },
  { name: "Calcium Hydroxyapatite", category: "Supplement", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "500" },
  { name: "Potassium Citrate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Potassium Chloride", category: "Supplement", defaultForm: "Powder", defaultUnit: "mg", defaultDose: "300" },
  { name: "Iodine (Lugol's)", category: "Supplement", defaultForm: "Liquid", defaultUnit: "mg", defaultDose: "12.5" },
  { name: "Selenium (Selenomethionine)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mcg", defaultDose: "200" },
  { name: "Copper (Sebacate)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "2" },
  { name: "Molybdenum", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mcg", defaultDose: "500" },
  { name: "Manganese", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "5" },
  { name: "Chromium Picolinate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mcg", defaultDose: "200" },
  { name: "Vanadyl Sulfate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "10" },
  { name: "Lithium Orotate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "5" },
  { name: "Boron Glycinate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "3" },
  { name: "Silica (Orthosilicic Acid)", category: "Supplement", defaultForm: "Liquid", defaultUnit: "mg", defaultDose: "10" },
  { name: "Strontium Citrate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "340" },

  // ── ELECTROLYTES & HYDRATION ─────────────────────────────────────────────────
  { name: "Sodium Bicarbonate", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "5" },
  { name: "Electrolyte Mix (LMNT)", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "1" },
  { name: "Himalayan Pink Salt", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "3" },
  { name: "Creatine Monohydrate", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "5" },
  { name: "Creatine HCL", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "750" },
  { name: "Creatine Ethyl Ester", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1000" },
  { name: "Beta-Alanine", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "3.2" },
  { name: "L-Citrulline", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "6" },
  { name: "Citrulline Malate", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "8" },
  { name: "L-Arginine", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "3" },

  // ── AMINO ACIDS ──────────────────────────────────────────────────────────────
  { name: "Collagen Peptides", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "10" },
  { name: "L-Glutamine", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "5" },
  { name: "Glycine", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "3" },
  { name: "Taurine", category: "Supplement", defaultForm: "Powder", defaultUnit: "mg", defaultDose: "1000" },
  { name: "L-Lysine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1000" },
  { name: "L-Proline", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "L-Tryptophan", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "5-HTP (5-Hydroxytryptophan)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "L-Tyrosine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "N-Acetyl Tyrosine (NALT)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "350" },
  { name: "L-Phenylalanine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "DL-Phenylalanine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "L-Methionine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "L-Leucine", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "3" },
  { name: "BCAA (2:1:1)", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "5" },
  { name: "EAA (Essential Amino Acids)", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "10" },
  { name: "L-Theanine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "GABA", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "750" },
  { name: "Phenibut", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "L-Ornithine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Acetyl-L-Carnitine (ALCAR)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "L-Carnitine Tartrate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1000" },
  { name: "Propionyl-L-Carnitine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },

  // ── NOOTROPICS & COGNITIVE ───────────────────────────────────────────────────
  { name: "Alpha GPC", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "300" },
  { name: "CDP Choline (Citicoline)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "250" },
  { name: "Uridine Monophosphate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "250" },
  { name: "Bacopa Monnieri", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "300" },
  { name: "Lion's Mane Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Lion's Mane (Full Spectrum)", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "2" },
  { name: "Rhodiola Rosea", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "300" },
  { name: "Gotu Kola", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "450" },
  { name: "Ginkgo Biloba", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "120" },
  { name: "Panax Ginseng", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "American Ginseng", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Sulbutiamine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Phosphatidylserine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "Agmatine Sulfate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Vinpocetine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "10" },
  { name: "Huperzine A", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mcg", defaultDose: "100" },
  { name: "DMAE (Dimethylaminoethanol)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Centrophenoxine", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "250" },
  { name: "Noopept", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "10" },
  { name: "Aniracetam", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "750" },
  { name: "Oxiracetam", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "800" },
  { name: "Phenylpiracetam", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "Fasoracetam", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "20" },
  { name: "Coluracetam", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "20" },
  { name: "Piracetam", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1600" },
  { name: "Pramiracetam", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Nefiracetam", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "150" },
  { name: "Sunifiram", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "5" },
  { name: "Bromantane", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "50" },
  { name: "Meclofenoxate", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "PRL-8-53", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "5" },
  { name: "NSI-189", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "40" },
  { name: "Idebonone", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "45" },
  { name: "N-Acetyl Semax Amidate", category: "Peptide", defaultForm: "Nasal Spray", defaultUnit: "mcg", defaultDose: "300" },
  { name: "N-Acetyl Selank", category: "Peptide", defaultForm: "Nasal Spray", defaultUnit: "mcg", defaultDose: "200" },
  { name: "9-ME-BC", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "15" },

  // ── ADAPTOGENS & MUSHROOMS ───────────────────────────────────────────────────
  { name: "Ashwagandha KSM-66", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "600" },
  { name: "Ashwagandha Shoden", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "120" },
  { name: "Ashwagandha Sensoril", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "125" },
  { name: "Eleuthero (Siberian Ginseng)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Schisandra Chinensis", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Holy Basil (Tulsi)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "300" },
  { name: "Astragalus Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Reishi Mushroom", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Chaga Mushroom", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "2" },
  { name: "Cordyceps Militaris", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Cordyceps Sinensis", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Turkey Tail (PSK)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Maitake Mushroom", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Shiitake Mushroom Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Tremella Mushroom", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "1" },
  { name: "Agarikon Mushroom", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Maca Root (Black)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1000" },
  { name: "Maca Root (Red)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1000" },
  { name: "Mucuna Pruriens (L-Dopa)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "300" },
  { name: "Jiaogulan (Gynostemma)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "450" },
  { name: "He Shou Wu (Fo-Ti)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Morinda Officinalis", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Cistanche Tubulosa", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "250" },

  // ── LONGEVITY & NAD+ ─────────────────────────────────────────────────────────
  { name: "NMN (Nicotinamide Mononucleotide)", category: "Supplement", defaultForm: "Powder", defaultUnit: "mg", defaultDose: "500" },
  { name: "NR (Nicotinamide Riboside)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "300" },
  { name: "Resveratrol (Trans)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Pterostilbene", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "PQQ (Pyrroloquinoline Quinone)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "20" },
  { name: "CoQ10 (Ubiquinone)", category: "Supplement", defaultForm: "Softgel", defaultUnit: "mg", defaultDose: "100" },
  { name: "Ubiquinol", category: "Supplement", defaultForm: "Softgel", defaultUnit: "mg", defaultDose: "100" },
  { name: "Berberine HCL", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Dihydroberberine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "Ca-AKG (Calcium Alpha-Ketoglutarate)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1000" },
  { name: "Spermidine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1" },
  { name: "Fisetin", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "Apigenin", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "50" },
  { name: "Quercetin Phytosome", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "250" },
  { name: "Quercetin (Standard)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Luteolin", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "Kaempferol", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "TMG (Trimethylglycine)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "GlyNAC", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1000" },
  { name: "Hyaluronic Acid", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Pyrroloquinoline Quinone (PQQ)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "20" },
  { name: "Urolithin A", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Ergothioneine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "5" },
  { name: "Taurine (High Dose)", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "3" },
  { name: "Metformin", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "500" },
  { name: "Acarbose", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "50" },
  { name: "Rapamycin (Sirolimus)", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "2" },
  { name: "Dasatinib", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "100" },
  { name: "Navitoclax", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "50" },

  // ── ANTIOXIDANTS & DETOX ─────────────────────────────────────────────────────
  { name: "NAC (N-Acetyl Cysteine)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "600" },
  { name: "S-Acetyl Glutathione", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Liposomal Glutathione", category: "Supplement", defaultForm: "Liquid", defaultUnit: "mg", defaultDose: "400" },
  { name: "R-Alpha Lipoic Acid", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Na-R-ALA", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "Astaxanthin", category: "Supplement", defaultForm: "Softgel", defaultUnit: "mg", defaultDose: "4" },
  { name: "Curcumin (C3 Complex)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Longvida Curcumin", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Curcumin + Piperine", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Bromelain", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Milk Thistle (Silymarin)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "150" },
  { name: "NACET", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "50" },
  { name: "Sulforaphane", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "50" },
  { name: "Spirulina", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "3" },
  { name: "Chlorella", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "3" },
  { name: "Modified Citrus Pectin", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "5" },
  { name: "Zeolite (Clinoptilolite)", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "1" },
  { name: "Activated Charcoal", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1000" },
  { name: "Pycnogenol (Pine Bark)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "Grape Seed Extract (OPC)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "150" },
  { name: "Green Tea Extract (EGCG)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },

  // ── GUT HEALTH ───────────────────────────────────────────────────────────────
  { name: "TUDCA", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "UDCA", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "250" },
  { name: "Betaine HCL", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "650" },
  { name: "Ox Bile", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Digestive Enzymes (Broad)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1" },
  { name: "Protease Enzymes", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Lipase Enzymes", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Probiotics (Multi-Strain)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "billion CFU", defaultDose: "50" },
  { name: "Lactobacillus Rhamnosus GG", category: "Supplement", defaultForm: "Capsule", defaultUnit: "billion CFU", defaultDose: "10" },
  { name: "Bifidobacterium Longum", category: "Supplement", defaultForm: "Capsule", defaultUnit: "billion CFU", defaultDose: "5" },
  { name: "Saccharomyces Boulardii", category: "Supplement", defaultForm: "Capsule", defaultUnit: "billion CFU", defaultDose: "5" },
  { name: "Akkermansia Muciniphila", category: "Supplement", defaultForm: "Capsule", defaultUnit: "million AFU", defaultDose: "15" },
  { name: "Colostrum", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "2" },
  { name: "Lactoferrin", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "250" },
  { name: "Psyllium Husk", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "5" },
  { name: "Inulin (Prebiotic)", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "5" },
  { name: "FOS (Fructooligosaccharides)", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "3" },
  { name: "GOS (Galactooligosaccharides)", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "3" },
  { name: "Slippery Elm Bark", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "2" },
  { name: "Deglycyrrhizinated Licorice (DGL)", category: "Supplement", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "380" },
  { name: "Marshmallow Root", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "L-Glutamine (Gut)", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "10" },
  { name: "Artichoke Leaf Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "320" },
  { name: "Dandelion Root Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },

  // ── SLEEP & STRESS ───────────────────────────────────────────────────────────
  { name: "Melatonin (Low Dose)", category: "Supplement", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "0.3" },
  { name: "Melatonin (High Dose)", category: "Supplement", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "5" },
  { name: "Magnesium Glycinate (Sleep)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "L-Theanine + Melatonin", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Valerian Root", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "300" },
  { name: "Passionflower Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "350" },
  { name: "Lemon Balm Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "300" },
  { name: "Chamomile Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Lavender Oil (Silexan)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "80" },
  { name: "Kava Root Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "250" },
  { name: "CBD (Full Spectrum)", category: "Supplement", defaultForm: "Oil", defaultUnit: "mg", defaultDose: "25" },
  { name: "CBD (Isolate)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "25" },
  { name: "CBN (Cannabinol)", category: "Supplement", defaultForm: "Oil", defaultUnit: "mg", defaultDose: "10" },
  { name: "Magnolia Bark Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Phosphatidylserine (Sleep)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Jujube Seed Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Glycine (Sleep)", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "3" },
  { name: "Inositol (Sleep)", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "2" },

  // ── HORMONAL SUPPORT ─────────────────────────────────────────────────────────
  { name: "Tongkat Ali (100:1)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Tongkat Ali (LJ100)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "Fadogia Agrestis", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "600" },
  { name: "Shilajit (PrimaVie)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "250" },
  { name: "DIM (Diindolylmethane)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Calcium D-Glucarate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Nettle Root Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "300" },
  { name: "Saw Palmetto", category: "Supplement", defaultForm: "Softgel", defaultUnit: "mg", defaultDose: "320" },
  { name: "Pygeum Africanum", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "Beta-Sitosterol", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Chrysin", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "7-Keto DHEA", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "100" },
  { name: "Tribulus Terrestris", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "650" },
  { name: "Fenugreek Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "600" },
  { name: "Vitex (Chaste Tree Berry)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Black Cohosh", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "40" },
  { name: "Red Clover Isoflavones", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "40" },
  { name: "DHEA", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "25" },
  { name: "Pregnenolone", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "50" },
  { name: "Enclomiphene", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "12.5" },
  { name: "Clomiphene", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "25" },
  { name: "Tamoxifen (Nolvadex)", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "20" },
  { name: "Anastrozole (Arimidex)", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "0.5" },
  { name: "Exemestane (Aromasin)", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "12.5" },

  // ── CARDIOVASCULAR ───────────────────────────────────────────────────────────
  { name: "Garlic (Allicin)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "600" },
  { name: "Aged Garlic Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "600" },
  { name: "Hawthorn Berry", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "450" },
  { name: "Nattokinase", category: "Supplement", defaultForm: "Capsule", defaultUnit: "FU", defaultDose: "2000" },
  { name: "Serrapeptase", category: "Supplement", defaultForm: "Capsule", defaultUnit: "SPU", defaultDose: "120000" },
  { name: "Lumbrokinase", category: "Supplement", defaultForm: "Capsule", defaultUnit: "U", defaultDose: "20" },
  { name: "Red Yeast Rice", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "600" },
  { name: "Bergamot Extract (BPF)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Policosanol", category: "Supplement", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "10" },
  { name: "Citrus Bergamot", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Grape Seed Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "150" },
  { name: "Niacin (Flush)", category: "Supplement", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "500" },
  { name: "L-Carnitine (Heart)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1000" },
  { name: "Taurine (Cardio)", category: "Supplement", defaultForm: "Powder", defaultUnit: "mg", defaultDose: "2000" },
  { name: "CoQ10 (High Dose)", category: "Supplement", defaultForm: "Softgel", defaultUnit: "mg", defaultDose: "300" },

  // ── BLOOD SUGAR & METABOLIC ──────────────────────────────────────────────────
  { name: "Ceylon Cinnamon", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Gymnema Sylvestre", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Bitter Melon Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Alpha Lipoic Acid (ALA)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "600" },
  { name: "Banaba Leaf Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "24" },
  { name: "White Mulberry Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Salacia Root", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Chromium GTF", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mcg", defaultDose: "400" },
  { name: "Vanadium (BMOV)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "10" },

  // ── JOINT & BONE ─────────────────────────────────────────────────────────────
  { name: "Glucosamine Sulfate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1500" },
  { name: "Chondroitin Sulfate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1200" },
  { name: "MSM (Methylsulfonylmethane)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1000" },
  { name: "UC-II Collagen", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "40" },
  { name: "Type II Collagen", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1000" },
  { name: "Boswellia Serrata (AKBA)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Cissus Quadrangularis", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Cetyl Myristoleate", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "350" },
  { name: "Strontium (Bone)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "680" },
  { name: "Ipriflavone", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Silicon Dioxide (Bone)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "50" },

  // ── THYROID & ENERGY ─────────────────────────────────────────────────────────
  { name: "Iodine + Iodide (Lugol's)", category: "Supplement", defaultForm: "Liquid", defaultUnit: "mg", defaultDose: "12.5" },
  { name: "Kelp (Natural Iodine)", category: "Supplement", defaultForm: "Tablet", defaultUnit: "mcg", defaultDose: "225" },
  { name: "Tyrosine (Thyroid)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Ashwagandha (Thyroid)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "600" },
  { name: "Bladderwrack", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Thyroid Glandular (Desiccated)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "65" },

  // ── IMMUNE SUPPORT ───────────────────────────────────────────────────────────
  { name: "Elderberry Extract", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Echinacea Purpurea", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "400" },
  { name: "Andrographis", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "300" },
  { name: "Beta-Glucan (1,3/1,6)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "250" },
  { name: "Cat's Claw (TOA-free)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "300" },
  { name: "Olive Leaf Extract (Oleuropein)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "500" },
  { name: "Monolaurin", category: "Supplement", defaultForm: "Capsule", defaultUnit: "g", defaultDose: "2" },
  { name: "Transfer Factor (4Life)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "1" },
  { name: "Thymus Glandular", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "250" },
  { name: "Arabinogalactan", category: "Supplement", defaultForm: "Powder", defaultUnit: "g", defaultDose: "3" },

  // ── PEPTIDES: HEALING & RECOVERY ─────────────────────────────────────────────
  { name: "BPC-157", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "250" },
  { name: "BPC-157 (Arginate)", category: "Peptide", defaultForm: "Capsule", defaultUnit: "mcg", defaultDose: "500" },
  { name: "TB-500", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "500" },
  { name: "Thymosin Beta-4", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "2" },
  { name: "TB-500 + BPC-157 (Blend)", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "10" },
  { name: "GHK-Cu", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "2" },
  { name: "GHK-Cu (Topical)", category: "Peptide", defaultForm: "Cream", defaultUnit: "mg", defaultDose: "10" },
  { name: "KPV", category: "Peptide", defaultForm: "Capsule", defaultUnit: "mcg", defaultDose: "500" },
  { name: "ARA-290", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "4" },
  { name: "LL-37", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "100" },
  { name: "Pentosan Polysulfate", category: "Compound", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "200" },
  { name: "VIP (Vasoactive Intestinal Peptide)", category: "Peptide", defaultForm: "Nasal Spray", defaultUnit: "mcg", defaultDose: "50" },
  { name: "PDA (MOTSC Analogue)", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "5" },
  { name: "Larazotide Acetate (AT-1001)", category: "Peptide", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "0.5" },
  { name: "RG3 (Ginsenoside)", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "5" },
  { name: "Synapsin (RG3 + NAD+)", category: "Peptide", defaultForm: "Nasal Spray", defaultUnit: "mcg", defaultDose: "500" },
  { name: "Adamax", category: "Peptide", defaultForm: "Nasal Spray", defaultUnit: "mcg", defaultDose: "100" },

  // ── PEPTIDES: METABOLIC & GH ─────────────────────────────────────────────────
  { name: "Semaglutide", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "0.25" },
  { name: "Tirzepatide", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "2.5" },
  { name: "Retatrutide", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "1" },
  { name: "Cagrilintide", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "0.16" },
  { name: "Tesamorelin", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "2" },
  { name: "Ipamorelin", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "200" },
  { name: "CJC-1295 (No DAC)", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "100" },
  { name: "CJC-1295 (With DAC)", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "500" },
  { name: "Mod GRF 1-29", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "100" },
  { name: "Sermorelin", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "300" },
  { name: "Hexarelin", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "200" },
  { name: "GHRP-2", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "100" },
  { name: "GHRP-6", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "100" },
  { name: "AOD-9604", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "300" },
  { name: "HGH Frag 176-191", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "250" },
  { name: "MK-677 (Ibutamoren)", category: "Peptide", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "25" },
  { name: "IGF-1 LR3", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "50" },
  { name: "IGF-1 DES", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "50" },
  { name: "Mechano Growth Factor (MGF)", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "200" },
  { name: "MOTS-c", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "5" },
  { name: "SS-31 (Elamipretide)", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "10" },
  { name: "5-Amino-1MQ", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "50" },
  { name: "SR-9009 (Stenabolic)", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "20" },
  { name: "GW-501516 (Cardarine)", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "10" },
  { name: "C-60 (Fullerene)", category: "Supplement", defaultForm: "Oil", defaultUnit: "mg", defaultDose: "1" },

  // ── PEPTIDES: NEUROLOGICAL & COGNITIVE ───────────────────────────────────────
  { name: "Selank", category: "Peptide", defaultForm: "Nasal Spray", defaultUnit: "mcg", defaultDose: "200" },
  { name: "Semax", category: "Peptide", defaultForm: "Nasal Spray", defaultUnit: "mcg", defaultDose: "200" },
  { name: "P21", category: "Peptide", defaultForm: "Nasal Spray", defaultUnit: "mcg", defaultDose: "500" },
  { name: "Dihexa", category: "Peptide", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "10" },
  { name: "Pinealon", category: "Peptide", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "5" },
  { name: "FGL (Fibroblast Growth Factor Loop)", category: "Peptide", defaultForm: "Nasal Spray", defaultUnit: "mcg", defaultDose: "500" },
  { name: "DSIP (Deep Sleep Inducing Peptide)", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "100" },
  { name: "Cerebrolysin", category: "Compound", defaultForm: "Injection", defaultUnit: "ml", defaultDose: "5" },
  { name: "Cortexin", category: "Compound", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "10" },
  { name: "Noopept (Peptide)", category: "Peptide", defaultForm: "Nasal Spray", defaultUnit: "mcg", defaultDose: "10000" },
  { name: "BDNF (Brain-Derived)", category: "Peptide", defaultForm: "Nasal Spray", defaultUnit: "mcg", defaultDose: "100" },
  { name: "NGF (Nerve Growth Factor)", category: "Peptide", defaultForm: "Nasal Spray", defaultUnit: "mcg", defaultDose: "100" },
  { name: "Oxytocin", category: "Peptide", defaultForm: "Nasal Spray", defaultUnit: "IU", defaultDose: "20" },
  { name: "Vasopressin (ADH)", category: "Peptide", defaultForm: "Nasal Spray", defaultUnit: "IU", defaultDose: "20" },

  // ── PEPTIDES: LONGEVITY & IMMUNE ─────────────────────────────────────────────
  { name: "Epitalon", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "5" },
  { name: "Thymalin", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "10" },
  { name: "Thymosin Alpha-1", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "1500" },
  { name: "FoxO4-DRI", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "2" },
  { name: "Humanin", category: "Peptide", defaultForm: "Injection", defaultUnit: "mg", defaultDose: "2" },
  { name: "Klotho Peptide", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "100" },
  { name: "TA-65 (Telomerase Activator)", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "8" },
  { name: "Melanotan II", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "250" },
  { name: "PT-141 (Bremelanotide)", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "1000" },
  { name: "Kisspeptin-10", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "100" },
  { name: "GnRH (Gonadorelin)", category: "Peptide", defaultForm: "Injection", defaultUnit: "mcg", defaultDose: "100" },

  // ── SARMs & PERFORMANCE ──────────────────────────────────────────────────────
  { name: "LGD-4033 (Ligandrol)", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "5" },
  { name: "RAD-140 (Testolone)", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "10" },
  { name: "YK-11", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "5" },
  { name: "S-23", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "10" },
  { name: "Ostarine (MK-2866)", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "25" },
  { name: "Andarine (S4)", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "25" },
  { name: "LGD-3303", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "20" },
  { name: "AC-262 (Accadrine)", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "10" },
  { name: "ACP-105", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "5" },

  // ── MISC COMPOUNDS ───────────────────────────────────────────────────────────
  { name: "Tadalafil (Cialis)", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "5" },
  { name: "Sildenafil (Viagra)", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "50" },
  { name: "Modafinil", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "100" },
  { name: "Armodafinil", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "150" },
  { name: "Low Dose Naltrexone (LDN)", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "4.5" },
  { name: "Methylene Blue", category: "Compound", defaultForm: "Liquid", defaultUnit: "mg", defaultDose: "10" },
  { name: "Ivermectin", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "12" },
  { name: "Fenbendazole", category: "Compound", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "222" },
  { name: "Artemisinin", category: "Supplement", defaultForm: "Capsule", defaultUnit: "mg", defaultDose: "200" },
  { name: "Nicotine (Low Dose Patch)", category: "Compound", defaultForm: "Patch", defaultUnit: "mg", defaultDose: "7" },
  { name: "Selegiline (L-Deprenyl)", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "5" },
  { name: "Pioglitazone", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "15" },
  { name: "Canagliflozin (SGLT2i)", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "100" },
  { name: "Empagliflozin (SGLT2i)", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "10" },
  { name: "Fluvoxamine", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "50" },
  { name: "Ketamine (Intranasal)", category: "Compound", defaultForm: "Nasal Spray", defaultUnit: "mg", defaultDose: "50" },
  { name: "Hydroxychloroquine", category: "Compound", defaultForm: "Tablet", defaultUnit: "mg", defaultDose: "200" },
];
